apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: k8s-pd-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
